### DISCUSSION TITLE
[Select] Multiselect like tagging?

### DISCUSSION THREAD

**Discussion by littpi** [livewire/flux#1079] [Feature Requests] [answered]
Hello. I am looking on the document of Flux and seems there are no multiselect variant like [Vueform MultiSelect](https://github.com/vueform/multiselect). Will it be considered to be implemented in the future?

**Comment by joshhanley** [comment]
@littpi thanks for the request! We have multiple select support here https://fluxui.dev/components/select#multiple-select

**Reply by littpi** [reply]
Hello @joshhanley . I know the multiple select support and actually they are very good. However, sometimes we want to show the selected elements to display and current multiple-select solutions seem not able to get to the effect? @PrinceMinky 's one is something I want to have though. I have tried to build a custom one but it is not using multiple select, but using `input` to store the value into an array.

**Comment by PrinceMinky** [comment]
@littpi am I right in assuming you want to incorporate the dismissible icons as seen in this screenshot?
![Screenshot 2025-02-20 153958](https://github.com/user-attachments/assets/5120fd4d-079a-4b80-81a8-727558aa54c7)

I did build something similar, work in progress:
![Screenshot 2025-02-20 154047](https://github.com/user-attachments/assets/8cf5ee27-0f07-4ea2-957b-36b6f1b2e424)

**Reply by littpi** [reply]
Hello @PrinceMinky . Yes I think the one you are working is what I want! Currently I have used `input` to store it into an array and use another function to wipe them out from the array. So I am thinking if it is possible to sync with multi-select.

**Comment by everully** [comment]
@littpi I’m experiencing the same issue. I was able to get it working by applying a bit of a hack.

In app.css:
```css
ui-selected > div {
    @apply overflow-x-auto;
    -ms-overflow-style: none;
    scrollbar-width: none;
}

ui-selected > div {
    @apply flex p-0 justify-start items-center;
}

ui-selected div > div > div {
    @apply w-0!;
}

ui-selected > div > div:not(:first-child)::before {
    content: ", ";
}
```

And in the select component, I added a custom button slot using <flux:select.selected :max="1000" />:

```blade
<flux:select variant="listbox" multiple >
    <x-slot name="button">
        <flux:select.button>
            <flux:select.selected :max="1000" />
        </flux:select.button>
    </x-slot>

    {{-- Options here  --}}
</flux:select>
```

![Screenshot 2025-04-23 at 11 55 03](https://github.com/user-attachments/assets/45cb99fe-fa42-4fa8-b098-eba6c97588ec)

Looking forward to official support for this feature in Flux!
