### DISCUSSION TITLE
Required asterisk for form elements

### DISCUSSION THREAD

**Discussion by seabasss** [livewire/flux#1155] [Feature Requests]
It would be great to be able to just add "required" or something like "required-label" to a flux form element to display a required asterisk next to the label.
I've found badge, but it's a little clumsy to restyle and seems like a hijack.

```html
<flux:select variant="listbox" searchable label="Category" required>

<flux:select variant="listbox" searchable label="Category" required-label="*">

<flux:select variant="listbox" searchable label="Category" badge="*">
```

**Comment by seabasss** [comment]
Some googled examples of the standard asterisk that people are used to see:

![wpforms-required-field-form-builder-2441776569](https://github.com/user-attachments/assets/9eda7b29-53f6-432a-b96f-da7f467203bb)
![required-fields](https://github.com/user-attachments/assets/3e42ea9e-99f6-4323-a53d-8cdcdcbe7ca9)
![account-creation-page-after-non-required-field-creation-1579877559](https://github.com/user-attachments/assets/26eb7a94-ccbc-4763-b373-34548ce7edf3)

I mean, you could pick how you want it to look. Doesn't even have to be red or an asterisk as long as it gets the point across. I just want a dedicated, simple way to highlight a form field as required. Add a class to it, and people can re-style if they're not happy with the default look, or they can skip using the required attribute and create their own.

Small thing, but flux is in the details :)

**Comment by Cbrad24** [comment]
An option if you want to implement your own style:
(Untested with Tailwind 4, definitely works with 3)

![image](https://github.com/user-attachments/assets/fc668b54-265d-43d8-ac41-fa0ed0aac798)

Add this to your `app.css` or relevant file:
```css
[data-flux-label].required {
    @apply after:content-['*'] after:ml-0.5 after:text-red-500;
}
```
Run `npm run build`

Then setup like so:
```blade
<form wire:submit="search">
    <flux:field>
        {{-- Note the class="required" here... --}}
        <flux:label class="required">Domain</flux:label>

        <div class="flex items-center justify-start gap-2">
            <flux:input
                wire:model="domain"
                placeholder="domain.com"
                icon="magnifying-glass"
                autofocus
                clearable
            />

            <flux:button variant="primary" type="submit">
                {{ __('app.buttons.search') }}
            </flux:button>
        </div>

        <flux:error name="domain" />
    </flux:field>
</form>
```

**Reply by seabasss** [reply]
Thank you! The point is to be able to do it on the short form syntax. Maybe I can target the label using the css + symbol. Would still love a simple, dedicated required attribute that takes care of it :)

**Comment by JurgenThijs** [comment]
This would be handy

```html
<flux:input
    name="email"
    label="Email address"
    required
    required-indicator="asterisk" 
/>
```

Or:

```html
<flux:input
    name="email"
    label="Email address"
    required
    required-indicator="text:Verplicht"
/>
```

**Comment by JurgenThijs** [comment]
I am now finding https://fluxui.dev/components/field#flux:label

So you can use 
```html
<flux:label badge="Required">Name</flux:label>
```

**Reply by JurgenThijs** [reply]
And you can even do

```html
<flux:label>
    <x-slot:badge>
        <flux:icon.academic-cap />
    </x-slot:badge>
    Name
</flux:label>
```

**Reply by seabasseee** [reply]
As stated in the original comment, this is already pointed out and not the requested solution. Thanks anyway.

**Comment by wojt-janowski** [comment]
My answer to this was deleted by Github when I reorganised accounts, so adding a slightly improved version here. Put the following in your `app.css` file. Then add the `required` attribute to your elements. It works with text inputs as well as selects (both the standard and listbox variants) and now also supports fields with descriptions. Not all browsers support CSS selectors but modern ones do. 

```css
/*
 * Add asterisk to required fields
 */
ui-label:has(+ div > input[required]),
ui-label:has(+ ui-description + div > input[required]),
ui-label:has(+ select[required]),
ui-label:has(+ ui-description + select[required]),
ui-label:has(+ ui-select[required]),
ui-label:has(+ ui-description + ui-select[required]),
ui-label:has(+ textarea[required]),
ui-label:has(+ ui-description + textarea[required]) {
    @apply after:ml-0.5 after:text-red-500 after:content-['*'];
}
```

**Reply by joffreypersia** [reply]
Hi @wojt-janowski 

I improved it for group input compatibility

```css
/*
 * Add asterisk to required fields
 */
ui-label:has(+ div > input[required]),
ui-label:has(+ ui-description + div > input[required]),
ui-label:has(+ select[required]),
ui-label:has(+ ui-description + select[required]),
ui-label:has(+ ui-select[required]),
ui-label:has(+ ui-description + ui-select[required]),
ui-label:has(+ textarea[required]),
ui-label:has(+ ui-description + textarea[required]),
ui-label:has(+ [data-flux-input-group] input[required]),
ui-label:has(+ div input[required]),
ui-label:has(+ div [data-flux-input][required]) {
    @apply after:ml-0.5 after:text-red-500 after:content-['*'];
}
```
