### DISCUSSION TITLE
Toast background colors

### DISCUSSION THREAD

**Discussion by timgavin** [livewire/flux#1211] [Feature Requests]
The toasts don't stand out on my site at all - they get lost in the background and don't pop. I would love to add background colors and my own icons. Would it be possible to allow `class` and `icon` attributes like other components?

If not, what about adding a class name to each variant? It's not consistent with the rest of the library, but something as simple as this would do the trick I think

```html
<div class="flux-toast-success">
    ...
</div>
```

And then we can style it in CSS

```css
.flux-toast-success {
    background: var(--color-green-600);
}
```

**Comment by jeffchown** [comment]
@timgavin When I call `Flux::toast('Test toast', variant: 'success')` I get markup that includes `data-variant="success" data-flux-toast-dialog` 

Have you tried CSS to target these?

**Reply by timgavin** [reply]
Good suggestion. It's pretty hacky, but it does work. Should be easier (and consistent) though; we should be able to add css and change the icons like the other components. And if Caleb changes from zinc to another color it's gonna break. 🤷‍♂️

```css
[data-flux-toast-dialog][data-variant='success'] .text-zinc-800,
[data-flux-toast-dialog][data-variant='success'] .text-zinc-500 {
    color: white !important;
}

[data-flux-toast-dialog][data-variant='success'] svg {
    color: white !important;
}

[data-variant='success'] > div {
    background-color: var(--color-green-500);
}
```
