### DISCUSSION TITLE
Flux Pro - Dependabot Integration

### DISCUSSION THREAD

**Discussion by renfordt** [livewire/flux#1663] [Feature Requests]
Hey guys,

I'm currently stuck with my dependabot configuration. 

I always get a `private_source_authentication_failure` error when running dependabot for composer, interestingly also for other packages like `laravel/framework`. Do you have an idea why this happens?

I tried already different URLs like `http-basic.composer.fluxui.dev`, `https://composer.fluxui.dev` and `http://composer.fluxui.dev` but non of them seem to work.

Maybe it would be good to add this also to the documentation.

```yml
version: 2
registries:
  composer-fluxui:
    type: composer-repository
    url: http://composer.fluxui.dev
    username: ${{ secrets.FLUX_USERNAME }}
    password: ${{ secrets.FLUX_LICENSE_KEY }}
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    target-branch: "dev"
    open-pull-requests-limit: 30
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    target-branch: "dev"
    open-pull-requests-limit: 30
    registries:
      - composer-fluxui
```

**Comment by lode** [comment]
@renfordt did you find a way to solve this?

**Reply by renfordt** [reply]
```yml

version: 2
registries:
  composer-fluxui:
    type: composer-repository
    url: https://composer.fluxui.dev
    username: "${{secrets.FLUX_USERNAME}}"
    password: "${{secrets.FLUX_LICENSE_KEY}}"
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    target-branch: "dev"
    open-pull-requests-limit: 20
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    target-branch: "dev"
    open-pull-requests-limit: 20
    registries:
      - composer-fluxui
```

This is my `dependabot.yml`

I guess the main error was that I mistakenly added the license and the user to the action secrets and not to the dependabot secrets.
