### DISCUSSION TITLE
Is there a way to override the TailwindCSS default color for focus outline?

### DISCUSSION THREAD

**Discussion by joffreypersia** [livewire/flux#1713] [Feature Requests]
Hi,

I am wondering if there is a way to overwrite the TailwindCSS (V4) colors that are used in FluxUI when we 'tab' on element, or even when we focus within an input field.

I tried
```css
    :root {
        --tw-ring-color: var(--color-primary-500);
    }
```
but it didn't work.

Have you an idea to avoid the brutal :

```css
:is([type=text],input:where(:not([type])),[type=email],[type=url],[type=password],[type=number],[type=date],[type=datetime-local],[type=month],[type=search],[type=tel],[type=time],[type=week],[multiple],textarea,select):focus {
  --tw-ring-color: var(--color-primary-500);
}
```

Thank you :)
