### DISCUSSION TITLE
Tabs should be responsive

### DISCUSSION THREAD

**Discussion by nezaboravi** [livewire/flux#265] [Feature Requests] [answered]
Love the tabs, but imho Tabs should be responsive and fold on mobile views. Currently page scrolls, which is how we would expect it to be.
Perhaps convert it to drop down as tailwindui does? Or any other solution but scrolling.

**Comment by mauritskorse** [comment]
Yep, I agree. I already made a mockup for the nav menu. Havent tried it for tabs though. 
See https://github.com/livewire/flux/discussions/258

**Comment by donnyxray** [comment]
Yes please! I've been trying ```overflow-x-auto``` on the ```flux:tabs``` section as a work-around, but to no avail.

As I imagine it will take a while for Team Flux to get to this - please post functional work-arounds if you have them.

**Reply by mauritskorse** [reply]
check this out: https://github.com/livewire/flux/discussions/258#discussioncomment-10832374

**Reply by donnyxray** [reply]
Awesome! Thank you.

**Reply by nezaboravi** [reply]
This is nice, but why? I do expect this to be done by library, without me hacking around. It is so common thing to have. 
i check what you did, and i dont know to do that my self, so i purchase library to solve it for me.

**Reply by helderneves91** [reply]
> This is nice, but why? I do expect this to be done by library, without me hacking around. It is so common thing to have. i check what you did, and i dont know to do that my self, so i purchase library to solve it for me.

although you are totally right, we're just helping each other

**Comment by helderneves91** [comment]
> Love the tabs, but imho Tabs should be responsive and fold on mobile views. Currently page scrolls, which is how we would expect it to be. Perhaps convert it to drop down as tailwindui does? Or any other solution but scrolling.

totally agree, and it's not only on mobile, if you use alot of tabs, it won't wrap.

As a workaround I use `<flux:tab.group class="overflow-auto">`.
<img width="569" alt="Captura de ecrã 2024-10-03, às 17 13 38" src="https://github.com/user-attachments/assets/d725bb5d-4d20-45d6-8219-e81fd1f95734">

**Comment by Cbrad24** [comment]
Something like this from the UI framework I'm migrating from works well too:
https://shoelace.style/components/tab-group#scrolling-tabs

![ShoelaceTabs](https://github.com/user-attachments/assets/63692513-fae8-4eee-bc1e-260540856edb)

Unfortunately the UX (User Experience) just feels a bit clunky with many tabs currently, as shown below:
https://fluxui.dev/components/tabs#dynamic-tabs

![FluxTabs](https://github.com/user-attachments/assets/63e62661-398e-4ffb-9f84-b53876b924bd)

And if you don't wrap your container in `overflow-x-auto` it will just overflow the entire container.

**Comment by doti-dominic** [comment]
Maybe this video by Adam Wathan (Tailwind CSS) offers some inspiration for a possible solution: https://www.youtube.com/watch?v=v9nHYcKeBw0

**Reply by mauritskorse** [reply]
Based on this video I actually made a small flux:responsive component that I can now wrap around the tabs:
```blade
@props([
    'scrollbar' => false
])

<div class="flex overflow-x-auto -mx-[var(--padding-x)] {{ $scrollbar ? '' : 'scrollbar-hidden' }}">
    <div class="px-[var(--padding-x)] grow">
        {{  $slot }}
    </div>
</div>
```

It requires some additional tailwind theme and utility classes though:
```css
/* Initializie padding variables*/
@theme {
    --padding: calc(var(--spacing) * 6 );
    --padding-y: var(--padding);
    --padding-x: var(--padding); 
    --padding-t: var(--padding-y);
    --padding-b: var(--padding-y);
    --padding-l: var(--padding-x);
    --padding-r: var(--padding-x);
}

@utility p-*{
    --padding: calc(var(--spacing) * --value(integer, [number]));
}
@utility py-*{
    --padding-y: calc(var(--spacing) * --value(integer, [number]));
}
@utility px-*{
    --padding-x: calc(var(--spacing) * --value(integer, [number]));
}
@utility pt-*{
    --padding-t: calc(var(--spacing) * --value(integer, [number]));
}
@utility pb-*{
    --padding-b: calc(var(--spacing) * --value(integer, [number]));
}
@utility pl-*{
    --padding-l: calc(var(--spacing) * --value(integer, [number]));
}
@utility pr-*{
    --padding-r: calc(var(--spacing) * --value(integer, [number]));
}
```
