### ISSUE TITLE
Manual dark mode not working in flux 2 pro?

### ISSUE THREAD

**Issue by yabdab** [livewire/flux#1111]
### Flux version

2.0.0

### Livewire version

3.5.20

### Tailwind version

4.0.6

### What is the problem?

I have my app.css to use dark mode based on selector.

```@custom-variant dark (&:where(.dark, .dark *));```

However, the systems preference ( in my case dark mode ) is used. The `dark` class is not added anywhere in my app.

All my other objects look ok, but the flux compoenents all appear in dark mode.

I do have `@fluxAppearance` just before `</head>` on my layout file.

### Code snippets

@custom-variant dark (&:where(.dark, .dark *));

### How do you expect it to work?

All flux components should NOT use dark mode by default.

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by jeffchown** [comment]
@yabdab When you add `@fluxAppearance` to your page/layout, it will add the following code:
```javascript
<style>
    :root.dark {
        color-scheme: dark;
    }
</style>
<script>
    window.Flux = {
        applyAppearance (appearance) {
            let applyDark = () => document.documentElement.classList.add('dark')
            let applyLight = () => document.documentElement.classList.remove('dark')

            if (appearance === 'system') {
                let media = window.matchMedia('(prefers-color-scheme: dark)')

                window.localStorage.removeItem('flux.appearance')

                media.matches ? applyDark() : applyLight()
            } else if (appearance === 'dark') {
                window.localStorage.setItem('flux.appearance', 'dark')

                applyDark()
            } else if (appearance === 'light') {
                window.localStorage.setItem('flux.appearance', 'light')

                applyLight()
            }
        }
    }

    window.Flux.applyAppearance(window.localStorage.getItem('flux.appearance') || 'system')
</script>
```
which will set Flux to 'system' by default if `'flux.appearance'` is not set in `window.localStorage`.

To manager Flux's dark mode manually, do not add `@fluxAppearance`.

**Comment by yabdab** [comment]
Yes, nothing is ever stored in localStorage, why is that?

Removing `@fluxAppearance` from head does fix my issue though since my app is not setup for darkmode.

I have tested Safari and Chrome for Mac and the localStorage item is never created.

**Comment by jeffchown** [comment]
@yabdab Perfect.  I'm glad removing `@fluxAppearance` worked for you.

I don't understand your question. Unless you add some script in your app e.g. `window.localStorage.setItem('flux.appearance', 'dark')` to set the `'flux.appearance'` or the '`flux.dark'` value (maybe in response to a menu, etc. - see the examples: https://fluxui.dev/docs/dark-mode#examples), then only if you add `@fluxApperance` will a related value be stored in `localStorage`.

**Comment by neilcorke** [comment]
@jeffchown 

I upgraded a project to V.2 today and everything looked good until this evening.  We don't have dark mode set up on this, but it is enabled on on Macbook.    Previously I had dark mode disabled, in tailwind.config.js  and removed @fluxAppearance but the text is stil white in flux:heading and other components.

Is there another step required to disable the dark mode now?

**Comment by jeffchown** [comment]
@neilcorke As this TW4 and Flux 2 are substantial upgrades, before we dig any deeper, have you?:
- run `php artisan view:clear`
- run `npm run build`
- cleared your browser's cache

After trying the above, if the problem still exists:
- Can you post a screenshot of what you are seeing and provide: your layout blade, view file, app.css and tailwind.config.js?

**Comment by neilcorke** [comment]
@jeffchown  Does Tailwind v.4 have  a tailwind.config.js file?

I am not seeing this now!

<img width="734" alt="Image" src="https://github.com/user-attachments/assets/8f935258-6b38-44b3-b801-0da051b3ed97" />

**Comment by neilcorke** [comment]
@jeffchown Here is a screenshot before the dark mode became active and another after

<img width="1267" alt="Image" src="https://github.com/user-attachments/assets/243270a4-7e22-40b4-af55-e636949cb952" />

<img width="1017" alt="Image" src="https://github.com/user-attachments/assets/6672a25b-5b65-44ad-a87d-b0c8cbc6e93d" />

Here is the Layout Blade

```blade
@props(['bodyClass' => '', 'title' => ''])

<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }} | {{ $title }} </title>

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet" />
    <link href="https://fonts.bunny.net/css?family=inter:400,500,600&display=swap" rel="stylesheet" />

    <!-- Splide CSS -->
    <script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/js/splide.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/css/splide.min.css">

    <!-- Scripts -->
    @vite(['resources/css/app.css', 'resources/js/app.js'])

    <!-- Styles -->
    @livewireStyles
{{--    @fluxAppearance--}}
    @cookieconsentscripts
</head>
<body @if($bodyClass) class="{{ $bodyClass }}" @endif>
    <div class="font-sans text-gray-900">
        {{ $slot }}
    </div>

    @livewireScriptConfig
    @fluxScripts
{{--    @cookieconsentview--}}
</body>
</html>

```


Here is the view blade

```blade
<x-frontend-layout title="Home">

  {{--Hero Section--}}
  <section class="bg-[url('https://cdn.falkcopperpans.com/public/images/hero/signature-pan-on-hob.webp')]
    bg-no-repeat bg-cover bg-center bg-gray-200 bg-blend-multiply mb-6">
    <div class="relative flex flex-col justify-end py-4 px-4 lg:px-8 max-w-(--breakpoint-xl) z-1 min-h-[25rem]">
      <div class="max-w-(--breakpoint-lg)">
        <flux:heading level="1" class="mb-1! text-white! text-2xl! lg:text-4xl! font-bold tracking-tight leading-tight">
          The Ultimate Cookware for Culinary Excellence
        </flux:heading>
        <flux:subheading class="mb-2 text-base! lg:text-lg! font-light! text-gray-200!">
          Handcrafted in Belgium and trusted by professional chefs and home cooks alike.
        </flux:subheading>
{{--        <flux:button variant="primary" href="{{ route('product.catalogue') }}">Shop Now</flux:button>--}}
      </div>
    </div>
  </section>

  {{--USP Bar--}}
  <section class="bg-gray-300 grid grid-cols-2 sm:grid-cols-2 md:grid-cols-4 lg:grid-cols-4 gap-4 mb-6">

    <div class="p-3 bg-gray-300">
      <flux:heading class="mb-0.5!">Copper Performance</flux:heading>
      <flux:subheading>Exceptional heat conductivity for precise temperature control.</flux:subheading>
    </div>

    <div class="p-3 bg-gray-300">
      <flux:heading class="mb-0.5!">Professional &amp; Home Use</flux:heading>
      <flux:subheading>Loved by Michelin-star chefs and passionate home cooks.</flux:subheading>
    </div>

    <div class="p-3 bg-gray-300">
      <flux:heading class="mb-0.5!">Timeless Durability</flux:heading>
      <flux:subheading>Heirloom quality hand-crafted to last for generations.</flux:subheading>
    </div>

    <div class="p-3 bg-gray-300 border border-gray-400">
      <flux:heading class="mb-0.5!">Sustainable & Safe</flux:heading>
      <flux:subheading>100% recyclable materials and PFOA-free.</flux:subheading>
    </div>
  </section>

  {{--Falk Collections Splide--}}
  <div
    x-data="{
        init() {
            new Splide(this.$refs.collections, {
                type: 'loop',
                autoplay: 'play',
                perPage: 4,
                pagination: false,
                gap: '1rem',
                perMove: 1,
                breakpoints: {
                    640: {
                        perPage: 1,
                    },
                    850:{
                        perPage: 2,
                    },
                    1068:{
                        perPage: 3,
                    },
                },
            }).mount()
        },
    }"
  >
    <section x-ref="collections" class="splide" aria-label="Falk Cookware Collections">


      <div class="splide__track">
        <ul class="splide__list">
          {{--Classical--}}
          <li class="splide__slide flex flex-col items-center justify-center pb-8">
            <img
              class="w-full"
              src="/img/classical-carousel.webp"
              alt="falk classical range"
            >
            <div class="pt-3 px-3 w-full border border-gray-300">
              <flux:heading level="3" class="mb-1! text-xl! font-medium! tracking-tight leading-tight">
                Classical Collection
              </flux:heading>
              <flux:subheading class="min-h-12">
                Our original range of solid copper cookware with solid cast handles and stainless steel handles.
              </flux:subheading>
              <div class="mt-3 mb-4 flex items-center gap-x-3">
                <flux:button
                  href="{{ route('collection.view', 'classical-range') }}"
                  variant="filled"
                  class="!rounded-sm"
                >
                  Read More
                </flux:button>
                <flux:button
                  href="{{ route('product.catalogue.collection', ['collection' => 'classical-range']) }}"
                  variant="primary"
                  class="!rounded-sm !bg-green-600 hover:!bg-green-600/90"
                >
                  Buy Now
                </flux:button>
              </div>
            </div>
          </li>
          {{--Signature--}}
          <li class="splide__slide flex flex-col items-center justify-center pb-8">
            <img
              class="w-full"
              src="https://picsum.photos/800/500?random=2"
              alt="falk signature range"
            >
            <div class="pt-3 px-3 w-full border borer-gray-300">
              <flux:heading level="3" class="text-xl! font-medium! tracking-tight leading-tight">
                Signature Collection
              </flux:heading>
              <flux:subheading class="min-h-12">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi.</flux:subheading>
              <div class="mt-3 mb-4 flex items-center gap-x-3">
                <flux:button
                  href="{{ route('collection.view', 'signature-range') }}"
                  variant="filled"
                  class="!rounded-sm"
                >
                  Read More
                </flux:button>
                <flux:button
                  href="{{ route('product.catalogue.collection', ['collection' => 'signature-range']) }}"
                  variant="primary"
                  class="!rounded-sm !bg-green-600 hover:!bg-green-600/90"
                >
                  Buy Now
                </flux:button>
              </div>
            </div>
          </li>
          {{--Copper Coeur--}}
          <li class="splide__slide flex flex-col items-center justify-center pb-8">
            <img
              class="w-full"
              src="/img/copper-coeur-carousel.webp"
              alt="falk copper coeur range"
            >
            <div class="pt-3 px-3 w-full border border-gray-300">
              <flux:heading level="3" class="text-xl! font-medium! tracking-tight leading-tight">
                Copper Coeur Collection
              </flux:heading>
              <flux:subheading class="min-h-12">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi.</flux:subheading>
              <div class="mt-3 mb-4 flex items-center gap-x-3">
                <flux:button
                  href="{{ route('collection.view', 'copper-coeur-range') }}"
                  variant="filled"
                  class="!rounded-sm"
                >
                  Read More
                </flux:button>
                <flux:button
                  href="{{ route('product.catalogue.collection', ['collection' => 'copper-coeur-range']) }}"
                  variant="primary"
                  class="!rounded-sm !bg-green-600 hover:!bg-green-600/90"
                >
                  Buy Now
                </flux:button>
              </div>
            </div>
          </li>
          {{--Fusion--}}
          <li class="splide__slide flex flex-col items-center justify-center pb-8">
            <img
              class="w-full"
              src="/img/fusion-carousel.webp"
              alt="falk fusion range"
            >
            <div class="pt-3 px-3 w-full border border-gray-300">
              <flux:heading level="3" class="text-xl! font-medium! tracking-tight leading-tight">
                Fusion Collection
              </flux:heading>
              <flux:subheading class="min-h-12">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi.</flux:subheading>
              <div class="mt-3 mb-4 flex items-center gap-x-3">
                <flux:button
                  href="{{ route('collection.view', 'fusion-range') }}"
                  variant="filled"
                  class="!rounded-sm"
                >
                  Read More
                </flux:button>
                <flux:button
                  href="{{ route('product.catalogue.collection', ['collection' => 'fusion-range']) }}"
                  variant="primary"
                  class="!rounded-sm !bg-green-600 hover:!bg-green-600/90"
                >
                  Buy Now
                </flux:button>
              </div>
            </div>
          </li>
          {{--Signature 2.0--}}
          <li class="splide__slide flex flex-col items-center justify-center pb-8">
            <img
              class="w-full"
              src="https://picsum.photos/800/500?random=5"
              alt="signature 2.0 range"
            >
            <div class="pt-3 px-3 w-full border border-gray-300">
              <flux:heading level="3" class="text-xl! font-medium! tracking-tight leading-tight">
                Signature 2.0 Collection
              </flux:heading>
              <flux:subheading class="min-h-12">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi.</flux:subheading>
              <div class="mt-3 mb-4 flex items-center gap-x-3">
                <flux:button
                  href="{{ route('collection.view', 'signature-2.0-range') }}"
                  variant="filled"
                  class="!rounded-sm"
                >
                  Read More
                </flux:button>
                <flux:button
                  href="{{ route('product.catalogue.collection', ['collection' => 'signature-2.0-range']) }}"
                  variant="primary"
                  class="!rounded-sm !bg-green-600 hover:!bg-green-600/90"
                >
                  Buy Now
                </flux:button>
              </div>
            </div>
          </li>
          {{--Flandria--}}
          <li class="splide__slide flex flex-col items-center justify-center pb-8">
            <img
              class="w-full"
              src="/img/flandria-carousel.webp"
              alt="falk flandria range"
            >
            <div class="pt-3 px-3 w-full border border-gray-300">
              <flux:heading level="3" class="text-xl! font-medium! tracking-tight leading-tight">
                Flandria Collection
              </flux:heading>
              <flux:subheading class="min-h-12">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</flux:subheading>
              <div class="mt-3 mb-4 flex items-center gap-x-3">
                <flux:button
                  href="{{ route('collection.view', 'flandria-range') }}"
                  variant="filled"
                  class="!rounded-sm"
                >
                  Read More
                </flux:button>
                <flux:button
                  href="{{ route('product.catalogue.collection', ['collection' => 'flandria-range']) }}"
                  variant="primary"
                  class="!rounded-sm !bg-green-600 hover:!bg-green-600/90"
                >
                  Buy Now
                </flux:button>
              </div>
            </div>
          </li>
        </ul>
      </div>
      {{--Buttons--}}
      <div class="relative -mt-5 mb-6">
        <div class="splide__arrows splide__arrows--ltr">
          <div class="flex items-center justify-center">
            <flux:button
              icon="forward"
              variant="filled"
              size="sm"
              class="splide__arrow--prev"
              aria-label="Next slide"
              aria-controls="theme-default-track"
            >
              Prev
            </flux:button>
            <div class="mx-2"></div>
            <flux:button
              icon-trailing="play-pause"
              variant="filled"
              size="sm"
              class="splide__toggle !mx-3"
              aria-label="Play/Pause"
            >
              <span class="splide__toggle__play">Play</span>
              <span class="splide__toggle__pause">Pause</span>
            </flux:button>
            <div class="mx-2"></div>
            <flux:button
              icon-trailing="forward"
              variant="filled"
              size="sm"
              class="splide__arrow--next"
              aria-label="Next slide"
              aria-controls="theme-default-track"
            >
              Next
            </flux:button>
          </div>
        </div>

      </div>
    </section>
  </div>
</x-frontend-layout>
```


And here is the app.css file

```css
@import 'tailwindcss';
@import '../../vendor/livewire/flux/dist/flux.css';
@plugin '@tailwindcss/forms';
@plugin '@tailwindcss/aspect-ratio';
@plugin '@tailwindcss/typography';
@plugin 'flowbite/plugin';

@source '../../vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php';
@source '../../node_modules/flowbite/**/*.js';
@source '../../vendor/livewire/flux-pro/stubs/**/*.blade.php';
@source '../../vendor/livewire/flux/stubs/**/*.blade.php';

@theme {
  --font-sans:
    Inter, ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji',
    'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';

  --color-accent: var(--color-accent);
  --color-accent-content: var(--color-accent-content);
  --color-accent-foreground: var(--color-accent-foreground);

  --color-falk-red: #640b1c;
  --color-cta-green: #50a469;
  --color-copper: #a46934;
  --color-copper-500: #c56a39;
  --color-copper-600: #b15f33;
  --color-copper-700: #9d542d;
}

/*
  The default border color has changed to `currentColor` in Tailwind CSS v4,
  so we've added these compatibility styles to make sure everything still
  looks the same as it did with Tailwind CSS v3.

  If we ever want to remove these styles, we need to add an explicit border
  color utility to any element that depends on these defaults.
*/
@layer base {
  *,
  ::after,
  ::before,
  ::backdrop,
  ::file-selector-button {
    border-color: var(--color-gray-200, currentColor);
  }
}


  /* Flux Green Scheme */
}
/* Re-assign Flux's gray of choice... */
@theme {
    --color-zinc-50: var(--color-slate-50);
    --color-zinc-100: var(--color-slate-100);
    --color-zinc-200: var(--color-slate-200);
    --color-zinc-300: var(--color-slate-300);
    --color-zinc-400: var(--color-slate-400);
    --color-zinc-500: var(--color-slate-500);
    --color-zinc-600: var(--color-slate-600);
    --color-zinc-700: var(--color-slate-700);
    --color-zinc-800: var(--color-slate-800);
    --color-zinc-900: var(--color-slate-900);
    --color-zinc-950: var(--color-slate-950);
}

@theme {
    --color-accent: var(--color-blue-500);
    --color-accent-content: var(--color-blue-600);
    --color-accent-foreground: var(--color-white);
}

@layer theme {
    .dark {
        --color-accent: var(--color-blue-500);
        --color-accent-content: var(--color-blue-400);
        --color-accent-foreground: var(--color-white);
    }
}





```
