### ISSUE TITLE
Radio group elements not having correct spacing applied

### ISSUE THREAD

**Issue by kyranb** [livewire/flux#1129]
### Flux version

v2.0.1

### Livewire version

v3.5.19

### Tailwind version

v4.0.7

### What is the problem?

First off all, V2 is amazing and thanks for all the work :) Have just found one small hiccup.

The Flux docs show the expected styling of the radio group as so:

![Image](https://github.com/user-attachments/assets/0c4f45b8-586a-48e3-8b55-0ff7e2e91fad)

Since upgrading to Flux 2/Tailwind 4, the radio group appears as follows:

![Image](https://github.com/user-attachments/assets/10065e13-136c-45c5-9e24-bd9648c749f5)

Also of note, I have no custom components.

### Flux/Blade Styling
```blade
<flux:radio.group wire:model="payment" label="Select your payment method">
    <flux:radio value="cc" label="Credit Card" checked />
    <flux:radio value="paypal" label="Paypal" />
    <flux:radio value="ach" label="Bank transfer" />
</flux:radio.group>
```

### Rendered HTML

```html
<ui-field class="min-w-0 [&amp;:not(:has([data-flux-field])):has([data-flux-control][disabled])>[data-flux-label]]:opacity-50 [&amp;:has(>[data-flux-radio-group][disabled])>[data-flux-label]]:opacity-50 [&amp;:has(>[data-flux-checkbox-group][disabled])>[data-flux-label]]:opacity-50 block data-flux-label:*:mb-3 [&amp;>[data-flux-label]:has(+[data-flux-description])]:mb-2 [&amp;>[data-flux-label]+[data-flux-description]]:mt-0 [&amp;>[data-flux-label]+[data-flux-description]]:mb-3 [&amp;>*:not([data-flux-label])+[data-flux-description]]:mt-3" data-flux-field="">
    <ui-label class="text-sm font-medium select-none text-zinc-800 dark:text-white" data-flux-label="" id="lofi-label-29fcf5938470d" aria-hidden="true">
    Select your payment method

    
    </ui-label>
        
        
        <ui-radio-group class="data-flux-field:*:mb-3 [&amp;>[data-flux-field]:has(>[data-flux-description])]:mb-4 [&amp;>[data-flux-field]:last-child]:mb-0!" wire:model="payment" label="Select your payment method" data-flux-radio-group="" role="radiogroup" aria-labelledby="lofi-label-29fcf5938470d">
        <ui-field class="min-w-0 [&amp;:not(:has([data-flux-field])):has([data-flux-control][disabled])>[data-flux-label]]:opacity-50 [&amp;:has(>[data-flux-radio-group][disabled])>[data-flux-label]]:opacity-50 [&amp;:has(>[data-flux-checkbox-group][disabled])>[data-flux-label]]:opacity-50 grid gap-x-3 gap-y-1.5 has-[[data-flux-label]~[data-flux-control]]:grid-cols-[1fr_auto] has-[[data-flux-control]~[data-flux-label]]:grid-cols-[auto_1fr] [&amp;>[data-flux-control]~[data-flux-description]]:row-start-2 [&amp;>[data-flux-control]~[data-flux-description]]:col-start-2 [&amp;>[data-flux-control]~[data-flux-error]]:col-span-2 [&amp;>[data-flux-control]~[data-flux-error]]:mt-1 [&amp;>[data-flux-label]~[data-flux-control]]:row-start-1 [&amp;>[data-flux-label]~[data-flux-control]]:col-start-2" data-flux-field="">
    <ui-radio class="flex size-[1.125rem] rounded-full mt-px outline-offset-2" value="cc" label="Credit Card" checked="checked" data-flux-control="" data-flux-radio="" tabindex="0" aria-checked="true" data-checked="" role="radio" aria-labelledby="lofi-label-71be43a4ef7ab" data-active="">
        <div class="shrink-0 size-[1.125rem] rounded-full text-sm text-zinc-700 dark:text-zinc-800 shadow-2xs [ui-radio[disabled]_&amp;]:opacity-75 [ui-radio[data-checked][disabled]_&amp;]:opacity-50 [ui-radio[disabled]_&amp;]:shadow-none [ui-radio[data-checked]_&amp;]:shadow-none flex justify-center items-center [ui-radio[data-checked]_&amp;>div]:block border border-zinc-300 dark:border-white/10 [ui-radio[disabled]_&amp;]:border-zinc-200 dark:[ui-radio[disabled]_&amp;]:border-white/5 [ui-radio[data-checked]_&amp;]:border-transparent data-indeterminate:border-transparent [ui-radio[disabled]_&amp;]:[ui-radio[data-checked]_&amp;]:border-transparent data-indeterminate:border-transparent [print-color-adjust:exact] bg-white dark:bg-white/10 [ui-radio[data-checked]_&amp;]:bg-[var(--color-accent)] [ui-radio[data-checked]_&amp;]:hover:bg-(--color-accent) [ui-radio[data-checked]_&amp;]:focus:bg-(--color-accent)" data-flux-radio-indicator="">
    <div class="hidden size-2 rounded-full bg-[var(--color-accent-foreground)]"></div>
</div>
    </ui-radio>

                    <ui-label class="text-sm font-medium select-none text-zinc-800 dark:text-white" data-flux-label="" id="lofi-label-71be43a4ef7ab" aria-hidden="true">
    Credit Card

    
    </ui-label>
        
        
        <div role="alert" aria-live="polite" aria-atomic="true" class="mt-3 text-sm font-medium text-red-500 dark:text-red-400 hidden" data-flux-error="">
    </div>
</ui-field>

    <ui-field class="min-w-0 [&amp;:not(:has([data-flux-field])):has([data-flux-control][disabled])>[data-flux-label]]:opacity-50 [&amp;:has(>[data-flux-radio-group][disabled])>[data-flux-label]]:opacity-50 [&amp;:has(>[data-flux-checkbox-group][disabled])>[data-flux-label]]:opacity-50 grid gap-x-3 gap-y-1.5 has-[[data-flux-label]~[data-flux-control]]:grid-cols-[1fr_auto] has-[[data-flux-control]~[data-flux-label]]:grid-cols-[auto_1fr] [&amp;>[data-flux-control]~[data-flux-description]]:row-start-2 [&amp;>[data-flux-control]~[data-flux-description]]:col-start-2 [&amp;>[data-flux-control]~[data-flux-error]]:col-span-2 [&amp;>[data-flux-control]~[data-flux-error]]:mt-1 [&amp;>[data-flux-label]~[data-flux-control]]:row-start-1 [&amp;>[data-flux-label]~[data-flux-control]]:col-start-2" data-flux-field="">
    <ui-radio class="flex size-[1.125rem] rounded-full mt-px outline-offset-2" value="paypal" label="Paypal" data-flux-control="" data-flux-radio="" tabindex="-1" aria-checked="false" role="radio" aria-labelledby="lofi-label-b6ffd5dd7a9fa">
        <div class="shrink-0 size-[1.125rem] rounded-full text-sm text-zinc-700 dark:text-zinc-800 shadow-2xs [ui-radio[disabled]_&amp;]:opacity-75 [ui-radio[data-checked][disabled]_&amp;]:opacity-50 [ui-radio[disabled]_&amp;]:shadow-none [ui-radio[data-checked]_&amp;]:shadow-none flex justify-center items-center [ui-radio[data-checked]_&amp;>div]:block border border-zinc-300 dark:border-white/10 [ui-radio[disabled]_&amp;]:border-zinc-200 dark:[ui-radio[disabled]_&amp;]:border-white/5 [ui-radio[data-checked]_&amp;]:border-transparent data-indeterminate:border-transparent [ui-radio[disabled]_&amp;]:[ui-radio[data-checked]_&amp;]:border-transparent data-indeterminate:border-transparent [print-color-adjust:exact] bg-white dark:bg-white/10 [ui-radio[data-checked]_&amp;]:bg-[var(--color-accent)] [ui-radio[data-checked]_&amp;]:hover:bg-(--color-accent) [ui-radio[data-checked]_&amp;]:focus:bg-(--color-accent)" data-flux-radio-indicator="">
    <div class="hidden size-2 rounded-full bg-[var(--color-accent-foreground)]"></div>
</div>
    </ui-radio>

                    <ui-label class="text-sm font-medium select-none text-zinc-800 dark:text-white" data-flux-label="" id="lofi-label-b6ffd5dd7a9fa" aria-hidden="true">
    Paypal

    
    </ui-label>
        
        
        <div role="alert" aria-live="polite" aria-atomic="true" class="mt-3 text-sm font-medium text-red-500 dark:text-red-400 hidden" data-flux-error="">
    </div>
</ui-field>

    <ui-field class="min-w-0 [&amp;:not(:has([data-flux-field])):has([data-flux-control][disabled])>[data-flux-label]]:opacity-50 [&amp;:has(>[data-flux-radio-group][disabled])>[data-flux-label]]:opacity-50 [&amp;:has(>[data-flux-checkbox-group][disabled])>[data-flux-label]]:opacity-50 grid gap-x-3 gap-y-1.5 has-[[data-flux-label]~[data-flux-control]]:grid-cols-[1fr_auto] has-[[data-flux-control]~[data-flux-label]]:grid-cols-[auto_1fr] [&amp;>[data-flux-control]~[data-flux-description]]:row-start-2 [&amp;>[data-flux-control]~[data-flux-description]]:col-start-2 [&amp;>[data-flux-control]~[data-flux-error]]:col-span-2 [&amp;>[data-flux-control]~[data-flux-error]]:mt-1 [&amp;>[data-flux-label]~[data-flux-control]]:row-start-1 [&amp;>[data-flux-label]~[data-flux-control]]:col-start-2" data-flux-field="">
    <ui-radio class="flex size-[1.125rem] rounded-full mt-px outline-offset-2" value="ach" label="Bank transfer" data-flux-control="" data-flux-radio="" tabindex="-1" aria-checked="false" role="radio" aria-labelledby="lofi-label-bf4940f0116a">
        <div class="shrink-0 size-[1.125rem] rounded-full text-sm text-zinc-700 dark:text-zinc-800 shadow-2xs [ui-radio[disabled]_&amp;]:opacity-75 [ui-radio[data-checked][disabled]_&amp;]:opacity-50 [ui-radio[disabled]_&amp;]:shadow-none [ui-radio[data-checked]_&amp;]:shadow-none flex justify-center items-center [ui-radio[data-checked]_&amp;>div]:block border border-zinc-300 dark:border-white/10 [ui-radio[disabled]_&amp;]:border-zinc-200 dark:[ui-radio[disabled]_&amp;]:border-white/5 [ui-radio[data-checked]_&amp;]:border-transparent data-indeterminate:border-transparent [ui-radio[disabled]_&amp;]:[ui-radio[data-checked]_&amp;]:border-transparent data-indeterminate:border-transparent [print-color-adjust:exact] bg-white dark:bg-white/10 [ui-radio[data-checked]_&amp;]:bg-[var(--color-accent)] [ui-radio[data-checked]_&amp;]:hover:bg-(--color-accent) [ui-radio[data-checked]_&amp;]:focus:bg-(--color-accent)" data-flux-radio-indicator="">
    <div class="hidden size-2 rounded-full bg-[var(--color-accent-foreground)]"></div>
</div>
    </ui-radio>

                    <ui-label class="text-sm font-medium select-none text-zinc-800 dark:text-white" data-flux-label="" id="lofi-label-bf4940f0116a" aria-hidden="true">
    Bank transfer

    
    </ui-label>
        
        
        <div role="alert" aria-live="polite" aria-atomic="true" class="mt-3 text-sm font-medium text-red-500 dark:text-red-400 hidden" data-flux-error="">
    </div>
</ui-field>
    </ui-radio-group>

        <div role="alert" aria-live="polite" aria-atomic="true" class="mt-3 text-sm font-medium text-red-500 dark:text-red-400 hidden" data-flux-error="">
    </div>
</ui-field>
```

### app.css
```css

@import 'tailwindcss';
@import '../../vendor/livewire/flux/dist/flux.css';

@plugin '@tailwindcss/forms';
@plugin '@tailwindcss/typography';

@source '../../vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php';
@source '../../vendor/livewire/flux-pro/stubs/**/*.blade.php';
@source '../../vendor/livewire/flux/stubs/**/*.blade.php';

/* Required for dark mode in Flux... */
@custom-variant dark (&:where(.dark, .dark *));

@theme {
  --font-sans:
    Inter, ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji',
    'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
}

/*
  The default border color has changed to `currentColor` in Tailwind CSS v4,
  so we've added these compatibility styles to make sure everything still
  looks the same as it did with Tailwind CSS v3.

  If we ever want to remove these styles, we need to add an explicit border
  color utility to any element that depends on these defaults.
*/
@layer base {
  *,
  ::after,
  ::before,
  ::backdrop,
  ::file-selector-button {
    border-color: var(--color-gray-200, currentColor);
  }
}
```

### How do you expect it to work?

I expect the correct spacing around the radio group elements as shown in the docs/prior to upgrading to V2.

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by jeffchown** [comment]
@kyranb Your example works as expected in my test app.  Could you have some CSS in parent tags and/or your layout file that is affecting the `flux:radio.group` on your end?  Also, have you run `php artisan view:clear` and `npm run build`?

![Image](https://github.com/user-attachments/assets/7d57a905-5d09-458b-a4cd-1195729812d2)

**Comment by kyranb** [comment]
I've run both `php artisan view:clear` and `nom run build`. Can't see any other CSS that is overriding it.

@jeffchown What does your `app.css` look like?

**Comment by jeffchown** [comment]
I don't have the two lines:

```
@source '../../vendor/livewire/flux-pro/stubs/**/*.blade.php';
@source '../../vendor/livewire/flux/stubs/**/*.blade.php';
```

app.css
```css
@import 'tailwindcss';
@import '../../vendor/livewire/flux/dist/flux.css';

/* Required for dark mode in Flux... */
@custom-variant dark (&:where(.dark, .dark *));

@plugin '@tailwindcss/forms';
@plugin '@tailwindcss/typography';

@source '../../vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php';

@theme {
  --font-sans:
    Figtree, ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji',
    'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
}

/*
  The default border color has changed to `currentColor` in Tailwind CSS v4,
  so we've added these compatibility styles to make sure everything still
  looks the same as it did with Tailwind CSS v3.

  If we ever want to remove these styles, we need to add an explicit border
  color utility to any element that depends on these defaults.
*/
@layer base {
  *,
  ::after,
  ::before,
  ::backdrop,
  ::file-selector-button {
    border-color: var(--color-gray-200, currentColor);
  }
}

@theme {
    --color-accent: var(--color-sky-600);
    --color-accent-content: var(--color-sky-600);
    --color-accent-foreground: var(--color-white);
}

@layer theme {
    .dark {
        --color-accent: var(--color-sky-600);
        --color-accent-content: var(--color-sky-400);
        --color-accent-foreground: var(--color-white);
    }
}
```
