### ISSUE TITLE
Sidebar scrolls with main content when it exceeds screen height

### ISSUE THREAD

**Issue by Drenth1** [livewire/flux#1660]
### Flux version

v2.1.6

### Livewire version

v3.6.3

### Tailwind version

v4.1.7

### Browser and Operating System

Mozilla Firefox and Microsoft Edge, Windows 11

### What is the problem?

When using the sidebar layout, when the content in the `<flux:main>` section exceeds the screen height, the sidebar scrolls with the main content.

Please see the image below.

1. The sidebar
2. The content that exceeds the screen height
3. The issue, the sidebar scrolls with the content instead of being sticky

![Image](https://github.com/user-attachments/assets/fc769164-4800-4aa8-9d0c-653dda0d7730)

### Code snippets

1. A minimal example that shows the issue (sidebar links omitted for brevity)

```blade
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" class="h-full">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        @vite('resources/css/app.css')
        @fluxAppearance
    </head>
    <body class="h-full">
        <flux:sidebar sticky stashable class="bg-zinc-50 dark:bg-zinc-900 border-r rtl:border-r-0 rtl:border-l border-zinc-200 dark:border-zinc-700">
            <flux:sidebar.toggle class="lg:hidden cursor-pointer" icon="x-mark" />

            {{-- Sidebar content. --}}
        </flux:sidebar>

        <flux:header class="lg:hidden">
            <flux:sidebar.toggle class="lg:hidden" icon="bars-3" inset="left"/>

            {{-- Sidebar content. --}}
        </flux:header>

        <flux:main class="space-y-6">
            <div class="bg-red-300 h-[1000px]">
                This is content that is very high and exceeds screen height!
            </div>
        </flux:main>

        @vite('resources/js/app.js')
        @fluxScripts
    </body>
</html>
```

2. app.css

```css
@import 'tailwindcss';
@import '../../vendor/livewire/flux/dist/flux.css';

@source '../../vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php';
@source '../../storage/framework/views/*.php';
@source '../**/*.blade.php';
@source '../**/*.js';

@font-face {
    font-family: Inter;
    src: url("../fonts/Inter-VariableFont.ttf");
}

@theme {
    --font-sans: 'Inter', ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji',
        'Segoe UI Symbol', 'Noto Color Emoji';
}

@custom-variant dark (&:where(.dark, .dark *));
```

### How do you expect it to work?

I would expect the sidebar to stay maximum height at all times, even when the main content exceeds the page height.
The main content should be scrollable but the sidebar should remain sticky.

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.
