### ISSUE TITLE
White background on input in dark mode by chrome autocomplete suggestion

### ISSUE THREAD

**Issue by mauritskorse** [livewire/flux#511]
Once again a weird chrome issue.

The built in autocomplete suggestions provided by Chrome cause the background color of the input fields to turn white when hovering over the suggestions. See the two screenshots (first is normal state, second is when hovering over the suggestions.)

![Image](https://github.com/user-attachments/assets/9c0d03ea-ccb8-442d-b47c-d6d87776d2bc)
![Image](https://github.com/user-attachments/assets/f3c6347b-d061-47fa-bd82-157b7099aab6)

My setup is a new laravel project, flux pro 1.0.14, tailwind uses darkMode through selector

```blade
  <flux:input type="search" icon="magnifying-glass" wire:model.live="query" placeholder="Search icons..." >
      <x-slot name="iconTrailing" class="flex gap-2">
          <flux:badge variant="pill" size="sm">{{ $this->iconCount }} icons</flux:badge>
          <flux:button size="sm" variant="subtle" iconVariant="outline" icon="tabler.filter" class="-mr-1" />
      </x-slot>
  </flux:input>
``` 

```js
// tailwind.config.js
import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        "./vendor/livewire/flux-pro/stubs/**/*.blade.php",
        "./vendor/livewire/flux/stubs/**/*.blade.php",
    ],
    darkMode: 'selector',
    //...
}
````

To fix the issue I could add the following css:
```css
body.dark input:-webkit-autofill,
body.dark input:-webkit-autofill:hover, 
body.dark input:-webkit-autofill:focus, 
body.dark input:-webkit-autofill:active{
    -webkit-background-clip: text;
    -webkit-text-fill-color: #ffffff;
    transition: background-color 5000s ease-in-out 0s;
    box-shadow: inset 0 0 20px 20px #23232329;
    caret-color: white;
}
```
