### ISSUE TITLE
Dark Mode issue: Flashbang. Help!

### ISSUE THREAD

**Issue by kyledoesdev** [livewire/flux#883]
### Flux version

1.1.0

### Livewire version

3.5.17

### What is the problem?

I recently updated flux to add in dark mode support to my app. However when I am in dark mode, the page quickly shows light mode before the dark mode theme is applied.

Below is a video:

https://github.com/user-attachments/assets/1f7dc680-abbb-4374-b39c-5f1f79062784

### Code snippets

Here is my tailwind config file:
```js
import forms from '@tailwindcss/forms';
import typography from '@tailwindcss/typography';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'selector',
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        "./vendor/livewire/flux-pro/stubs/**/*.blade.php",
        "./vendor/livewire/flux/stubs/**/*.blade.php",
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', 'sans-serif'],
            },

            colors: {
                accent: {
                    DEFAULT: 'var(--color-accent)',
                    content: 'var(--color-accent-content)',
                    foreground: 'var(--color-accent-foreground)',
                },
            },
        },
    },

    plugins: [forms, typography],
};

```

This is my layout file:
```html
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="preconnect" href="https://fonts.bunny.net">
        <link href="https://fonts.bunny.net/css?family=inter:400,500,600&display=swap" rel="stylesheet" />
        <link rel="stylesheet" type='text/css' href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css" />

        @include('layouts.prezet')

        <!-- Scripts -->
        @vite(['resources/css/app.css', 'resources/js/app.js', 'resources/css/prezet.css'])
        @fluxStyles
    </head>
    <body class="min-h-screen">
        <livewire:navigation />

        <!-- Page Content -->
        <flux:main container>
            <div class="relative mx-auto flex w-full max-w-8xl flex-auto justify-center sm:px-2 lg:px-8 xl:px-12">
                <div class="min-w-0 max-w-2xl flex-auto px-4 py-4 lg:max-w-none lg:pl-8 lg:pr-0 xl:px-16">
                    @if (isset($header))
                        <div class="flex justify-between">
                            <div class="w-full sm:w-auto">
                                <h5 class="text-2xl lg:text-4xl font-bold">
                                    {{ $header }}
                                </h5>
                            </div>
                            <div class="flex">
                                <x-socials />
                            </div>
                        </div>  
                        
                        <flux:separator />
                    @endif

                    {{ $slot }}
                </div>
            </div>
        </flux:main>

        @persist('toast')
            <flux:toast />
        @endpersist

        @fluxScripts
    </body>
</html>
```

This is my app.css file:
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

[class*=' devicon-'], [class^='devicon-'] {
	margin-left: auto;
	margin-right: auto;
}

[data-flux-editor] [data-slot="content"] code:not(pre code) {
    @apply text-zinc-900 dark:bg-zinc-200 !important;
}

[data-flux-editor] [data-slot="content"] pre {
    @apply text-zinc-900 dark:bg-zinc-200 !important;
}

[data-flux-editor] [data-slot="content"] pre > code {
    @apply text-zinc-900 dark:bg-zinc-200 !important;
}

@layer base {
    :root {
        --color-accent: var(--color-violet-500);
        --color-accent-content: var(--color-violet-600);
        --color-accent-foreground: var(--color-white);
    }

    .dark {
        --color-accent: var(--color-violet-500);
        --color-accent-content: var(--color-violet-400);
        --color-accent-foreground: var(--color-white);
    }
}
```
My vite.config.js file:
```js
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import prismjs from 'vite-plugin-prismjs';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/css/prezet.css',
                'resources/js/app.js'
            ],
            refresh: true,
        }),
        prismjs({
            languages: ['php', 'javascript', 'html', 'css', 'bash', 'typescript',], // Enables dynamic loading
            theme: 'tomorrow',
            css: true,
        })
    ],
});

```

### How do you expect it to work?

I assume I am making a noobie or stupid mistake somewhere with my configuration because from what I've seen, this is working out of the box for most people. I can add wire:navigate to my nav links which band aids the issue, but does not solve the problem for page load.

I would appreciate any help on this, I also reached out in the livewire discord but haven't heard back from any community members at the time of writing this.

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.
