### ISSUE TITLE
Editor: nested unordered lists are not styled correctly

### ISSUE THREAD

**Issue by gdebrauwer** [livewire/flux#982]
### Flux version

v1.1.2

### Livewire version

v3.5.18

### What is the problem?

When you create an ordered list within an existing ordered list (use 'tab' keyboard shortcut to do that), then that nested ordered list is styled correctly. When you do the same with unordered lists, then the nested unordered list is not styled (no circle before every item)

<img width="396" alt="Image" src="https://github.com/user-attachments/assets/6cea3983-3d56-405d-9a3b-4ca5bdced61a" />

### Code snippets

```php
class EditorPage extends Component
{
    public $content = <<<HTML
        <ol>
            <li><p>first line</p></li>
            <li>
                <p>second line</p>
                <ol>
                    <li>first nested line</li>
                    <li>second nested line</li>
                </ol>
            </li>
        </ol>
        <ul>
            <li><p>first line</p></li>
            <li>
                <p>second line</p>
                <ul>
                    <li>first nested line</li>
                    <li>second nested line</li>
                </ul>
            </li>
        </ul>
    HTML;

    public function render()
    {
        return <<<HTML
            <flux:editor wire:model="content" />
        HTML;
    }
}
```

### How do you expect it to work?

Nested unordered list should get same styling as the parent unordered list

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by joshhanley** [comment]
@gdebrauwer thanks for reporting! I've submitted a PR with a fix.

PR description below.

# The scenario

Currently if you have a nested unordered list, the main unordered list has bullet styles, but the nested one does not.

![Image](https://github.com/user-attachments/assets/3fd57c14-a778-4174-8295-5e920f6d6576)

```blade
<?php

use Livewire\Volt\Component;

new class extends Component {
    public $content = <<<HTML
        <ol>
            <li><p>first line</p></li>
            <li>
                <p>second line</p>
                <ol>
                    <li>first nested line</li>
                    <li>second nested line</li>
                </ol>
            </li>
        </ol>
        <ul>
            <li><p>first line</p></li>
            <li>
                <p>second line</p>
                <ul>
                    <li>first nested line</li>
                    <li>second nested line</li>
                </ul>
            </li>
        </ul>
    HTML;

};

?>

<div class="px-4">
    <flux:editor wire:model="content" />
</div>
```

# The problem

It looks like the bullet styles are being applied to unordered lists that are direct children of the content component where as for ordered lists the numeric styles are being applied to the list items inside an ordered list.

```css
[data-flux-editor] [data-slot="content"] > ol {
    margin-top: 1.1428571em;
    margin-bottom: 1.1428571em;
    padding-inline-start:1.5714286em;
}

[data-flux-editor] [data-slot="content"] > ul {
    list-style-type: disc;
    margin-top: 1.1428571em;
    margin-bottom: 1.1428571em;
    padding-inline-start:1.5714286em;
}

[data-flux-editor] [data-slot="content"] ol > li {
    list-style-type: decimal;
    padding-inline-start:.4285714em;
}

[data-flux-editor] [data-slot="content"] ul > li {
    padding-inline-start:.4285714em;
}
```

# The solution

This PR moves unordered list bullet style to the li elements instead of the ul elements to match how ordered lists are styled.

![Image](https://github.com/user-attachments/assets/6b31b858-66e2-48bd-8d7d-bb1b227e63d3)

Fixes livewire/flux#982
